baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Case Study Documentation'
theme = 'hugo-theme-techdoc'
sectionPagesmenu = 'main'

metaDataFormat = "yaml"

[params]

    # Source Code repository section
    description = "put your description" # displayed below title
    github_repository = "https://github.com/thingsym/hugo-theme-techdoc"
    version = "0.9.7"

    # Documentation Menu section
	# Menu style settings
	menu_style = "open-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar

	menu_exclusion = [
	    "archives",
	    "archive",
	    "blog",
	    "entry",
	    "post",
	    "posts",
	]


[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "HyperQube"
        url = "/"
        weight = 2

    [[menu.main]]
        name = "HyperProb"
        url = "/"
        weight = 3
